name: Generate Keystore
on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Android Keystore
        run: |
          keytool -genkey -v -keystore anishift.keystore -alias anishift -keypass anishift123 -storepass anishift123 -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=AniShift, OU=App, O=AniShift, L=Colombo, S=Western, C=LK"
      
      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: Keystore-File
          path: anishift.keystore